version: '3'

services:
  db:
    image: postgres:latest
    container_name: mr-pricer-postgres
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d # entrypoint script
    ports:
      - '65432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  db-store:
